package commons_lang4cj.utils

public class Charsets {
    public static const ISO_8859_1: String = CharEncoding.ISO_8859_1
    public static const US_ASCII: String = CharEncoding.US_ASCII
    public static const UTF_8: String = CharEncoding.UTF_8
    public static const UTF_16: String = CharEncoding.UTF_16
    public static const UTF_16BE: String = CharEncoding.UTF_16BE
    public static const UTF_16LE: String = CharEncoding.UTF_16LE
}

